#!/usr/bin/env python3
"""
Generate a vendor payload signing key + the matching vendor_keys[] C file.

Usage:
    python3 tools/generate_vendor_key.py [-f] [--profile test|production]

Writes a fresh ECDSA secp256k1 private key to payload_signing_key.pem (repo
root, gitignored) and writes the matching C file keys/<profile>/vendor_keys.c
containing the `vendor_keys[]` array the loader compiles against. The loader
verifies SD-card payload signatures against that public key, so the C file MUST
match the private key that signs payloads (tools/generate_signed_payload.py).

The profile selects which keys file the build uses (default: test). Always
build the loader with the SAME profile as the key you sign payloads with:

    python3 tools/generate_vendor_key.py --profile production
    VENDOR_KEYS_PROFILE=production idf.py build

Use -f/--force to overwrite an existing key without prompting. Override the
private key path with the VENDOR_SIGNING_KEY env var.
"""
import argparse
import os

from ecdsa import SigningKey, SECP256k1

DEFAULT_KEY_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "payload_signing_key.pem"
)
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def pubkey_bytes_to_c_array(pub_bytes):
    return ", ".join(f"0x{b:02x}" for b in pub_bytes)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-f", "--force", action="store_true", help="overwrite existing key without prompting"
    )
    parser.add_argument(
        "--profile",
        choices=("test", "production"),
        default="test",
        help="vendor key profile to write (default: test)",
    )
    args = parser.parse_args()

    key_path = os.environ.get("VENDOR_SIGNING_KEY", DEFAULT_KEY_PATH)

    if os.path.exists(key_path) and not args.force:
        answer = input(f"{key_path} exists. Overwrite? [y/N] ").strip().lower()
        if answer != "y":
            print("Aborted.")
            return

    priv_key = SigningKey.generate(curve=SECP256k1)
    with open(key_path, "wb") as f:
        f.write(priv_key.to_pem())
    print(f"Wrote {key_path}")

    pub_bytes = priv_key.get_verifying_key().to_string("uncompressed")

    keys_dir = os.path.join(REPO_ROOT, "keys", args.profile)
    os.makedirs(keys_dir, exist_ok=True)
    vendor_keys_c = os.path.join(keys_dir, "vendor_keys.c")
    with open(vendor_keys_c, "w") as f:
        f.write(f"// {args.profile.title()} vendor keys (generated by tools/generate_vendor_key.py).\n")
        f.write('#include "vendor_keys.h"\n\n')
        f.write("const bl_pubkey_t vendor_keys[] = {\n")
        f.write(f"    {{ .bytes = {{ {pubkey_bytes_to_c_array(pub_bytes)} }} }},\n")
        f.write("    BL_PUBKEY_END_OF_LIST\n")
        f.write("};\n")
        f.write("const bl_pubkey_t *pubkeys_boot[] = { vendor_keys, NULL };\n")
    print(f"Wrote {vendor_keys_c}")

    print("\nRemember to rebuild the loader so it embeds this pubkey:")
    print(f"    VENDOR_KEYS_PROFILE={args.profile} idf.py build")


if __name__ == "__main__":
    main()
